version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sphinx-autoapi
    versions:
    - 1.8.0
  - dependency-name: myst-parser
    versions:
    - 0.13.4
    - 0.13.6
  - dependency-name: pre-commit
    versions:
    - 2.11.0
    - 2.11.1
    - 2.12.0
    - 2.12.1
  - dependency-name: sphinx
    versions:
    - 3.5.0
    - 3.5.2
    - 3.5.3
    - 3.5.4
  - dependency-name: hypothesis
    versions:
    - 6.1.1
    - 6.2.0
    - 6.3.0
    - 6.3.4
    - 6.6.0
    - 6.8.1
    - 6.8.3
    - 6.8.4
    - 6.9.0
  - dependency-name: pylint
    versions:
    - 2.7.0
    - 2.7.2
    - 2.7.4
  - dependency-name: flake8-bugbear
    versions:
    - 20.11.1
    - 21.3.1
    - 21.3.2
    - 21.4.3
  - dependency-name: isort
    versions:
    - 5.7.0
    - 5.8.0
  - dependency-name: flake8-docstrings
    versions:
    - 1.6.0
  - dependency-name: flake8
    versions:
    - 3.9.0
  - dependency-name: pycodestyle
    versions:
    - 2.7.0
  - dependency-name: flogging
    versions:
    - 0.0.12
    - 0.0.13
  - dependency-name: pytest-xdist
    versions:
    - 2.2.1
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: jinja2
    versions:
    - 2.11.3
  - dependency-name: ruyaml
    versions:
    - 0.20.0
  - dependency-name: black
    versions:
    - 20.8b1
  - dependency-name: pytest-cov
    versions:
    - 2.11.1
  - dependency-name: flakehell
    versions:
    - 0.9.0
