comment: false
ignore:
- mloq/tests
coverage:
  status:
    patch: off
    project:
      default:
        target: auto
        threshold: 0%
        informational: true
        paths:
        - mloq
