comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true  # if true: only post the comment if coverage changes

github_checks:
  annotations: true

ignore:
- tests
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        informational: true
        paths:
        - ^src/mloq.*
