language: python
sudo: true
dist: bionic
services:
  - docker
cache: pip
before_cache:
  - chown -R travis:travis $HOME/.cache/pip
stages:
  - style
  - test
before_install:
  - env
_no_version_bump_commit: &_no_version_bump_commit
  - commit_message !~ /^Bump version/
_install: &_install
  - pip install --upgrade pip cython coverage[toml] codecov pytest ipython pipenv
  - pipenv install --skip-lock .
  - find . -wholename "*/tests/*" -type d -exec chmod 555 {} \;
_coverage: &_coverage
  - coverage run --concurrency=multiprocessing -m pytest
  - travis_retry coverage combine
matrix:
  fast_finish: true
  include:
    - stage: style
      name: Check code style on python 3.8
      if: *_no_version_bump_commit
      python: 3.8
      install:
        - pip install -r requirements-lint.txt
      script:
        - make check
    - stage: test
      name: Run tests on python 3.6
      if: *_no_version_bump_commit
      python: 3.6
      install: *_install
      script: *_coverage
    - stage: test
      name: Run tests on python 3.7
      if: *_no_version_bump_commit
      python: 3.7
      install: *_install
      script: *_coverage
    - stage: test
      name: Run tests on python 3.8
      if: *_no_version_bump_commit
      python: 3.8
      install: *_install
      script: *_coverage
      after_success:
        - codecov
notifications:
  email: false
