language: python
sudo: true
dist: bionic
services:
  - docker
cache: pip
before_cache:
  - chown -R travis:travis $HOME/.cache/pip
stages:
  - style_check
before_install:
  - env
matrix:
  fast_finish: true
  include:
    - stage: style_check
      name: Check code style on python 3.6
      if: commit_message !~ /^Bump version/
      python: 3.6
      install:
        - pip install -r requirements-lint.txt
      script:
        - make check
notifications:
  email: false
