comment: false
ignore:
- {{ project.project_name }}/tests
coverage:
  status:
    patch: off
    project:
      default:
        target: auto
        threshold: 0%
        informational: true
        paths:
        - {{ project.project_name }}
