name: Build package

on:
  push:
    branches:
      - {{default_branch}}
  pull_request:
    branches: [ master ]

jobs:
  build-source:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
            git fetch --prune --unshallow

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U setuptools twine wheel bumpversion

      - name: Create unique version for test.pypi
        run: |
          set -e
          git pull --no-edit origin {{default_branch}}
          version_file={{package_name}}/version.py
          current_version=$(grep __version__ $version_file | cut -d\" -f2)
          ts=$(date +%s)
          new_version="$current_version$ts"
          bumpversion --current-version $current_version --new-version $new_version patch $version_file

      - name: Build package
        run: |
          python setup.py --version
          python setup.py bdist_wheel sdist --format=gztar
          twine check dist/*

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{'{{'}} secrets.TEST_PYPI_PASS {{'}}'}}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true

  test-source:
    needs: build-source
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple {{package_name}}
          python -m pip install -r requirements-test.txt

      - name: Test package
        run: |
          mv {{package_name}}/tests ./tests
          rm -rf {{package_name}}
          pytest
