name: Release package

on:
  pull_request:
    branches:
      - {{defult_branch}}
    types: [closed]

jobs:
  Bump-version:
    if: github.repository_owner == '{{project_org}}'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        git config user.name "{{bot_name}}"
        git config user.email "{{bot_email}}"
        git config pull.ff only
        pip install bump2version
    - name: Run bump version
      run: |
        set -e
        git pull --no-edit origin {{default_branch}}
        version_file={{project_name}}/version.py
        current_version=$(grep __version__ $version_file | cut -d\" -f2)
        bumpversion --tag --current-version $current_version --commit patch $version_file
        git remote add {{bot_name}}-remote https://{{bot_name}}:$${{'{{'}} secrets.BOT_AUTH_TOKEN {{'}}'}}@github.com/$GITHUB_REPOSITORY
        git push --tags {{bot_name}}-remote HEAD:{{default_branch}}
        set +e

  Release-package:
    needs: Bump-version
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U setuptools twine wheel

      - name: Build package
        run: |
          python setup.py --version
          python setup.py bdist_wheel sdist --format=gztar
          twine check dist/*

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@{{default_branch}}
        with:
          user: __token__
          password: ${{'{{'}} secrets.PYPI_PASS {{'}}'}}
