# This yaml file contains all the information used by mloq to set up a new project.
# All values are strings, except `python_versions` and `requirements`
# that are lists of strings.
# `null` values are interpreted as missing values.
# ------------------------------------------------------------------------------

# `template` contains all the values that will be written in the generated files.
# They are loaded as a dictionary and passed to jinja2 to fill in the templates.
project:
  open_source:  # boolean
  ci:  # string
  git_init: # boolean
  git_push: # boolean

template:
  project_name:
  default_branch:
  owner:
  author:
  email:
  project_url:
  bot_name:
  bot_email:
  ci_python_version:
  ci_ubuntu_version:
  ci_extra:
  git_message:
