# This yaml file contains all the information used by mloq to set up the root
# files of a new project.
# All values are strings, except `python_versions` and `requirements`
# that are lists of strings.
# `null` values are interpreted as missing values.
# ------------------------------------------------------------------------------

# `template` contains all the values that will be written in the generated files.
# They are loaded as a dictionary and passed to jinja2 to fill in the templates.
project:
  open_source:  # boolean
  docker:  # boolean
  mlflow: # boolean

template:
  project_name:
  owner:
  author:
  email:
  copyright_year:
  copyright_holder:
  project_url:
  license:
  description:
  python_versions:
  docker_image:
  pyproject_extra:
