name: Bump version

on:
  push:
    branches:
      - master

jobs:
  Bump-version:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commit.message, 'Bump version') && github.repository_owner == 'fragiletech'"
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Install dependencies
      run: |
        git config user.name "fragile-bot"
        git config user.email "bot@fragile.tech"
        git config pull.ff only
        pip install bump2version
    - name: Run bump version
      run: |
        set -e
        git pull --no-edit origin master
        version_file=mloq/version.py
        current_version=$(grep __version__ $version_file | cut -d\" -f2)
        bumpversion --tag --current-version $current_version --commit patch $version_file
        git remote add fragile-bot-remote https://fragile-bot:$${{ secrets.BOT_AUTH_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git push --tags fragile-bot-remote HEAD:master
        set +e