name: Bump version

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  Bump-version:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        git config --global user.name "{{bot_name}}"
        git config --global user.email "{{bot_email}}"
        pip install bump2version
    - name: Run bump version
      env:
        BOT_AUTH_TOKEN: ${{ '{{' }} secrets.BOT_AUTH_TOKEN {{ '}}' }}
      run: |
        set -e
        git pull --no-edit origin master
        version_file={{project_name}}/version.py
        current_version=$(grep __version__ $version_file | cut -d\" -f2)
        bumpversion --tag --current-version $current_version --commit patch $version_file
        git remote add {{bot_name}}-remote https://{{bot_name}}:${BOT_AUTH_TOKEN}@github.com/$GITHUB_REPOSITORY
        git push --tags {{bot_name}}-remote HEAD:master
        set +e