name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    if: github.repository == 'fragiletech/ml-ops-quickstart'
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - run: |
            git fetch --prune --unshallow

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U setuptools twine wheel

      - name: Build package
        run: |
          python setup.py --version
          python setup.py sdist --format=gztar
          twine check dist/*

      - name: Publish package to TestPyPI
        if: "contains(github.event.head_commit.message, 'Bump version')"
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_PASS }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish package to PyPI
        if: "contains(github.event.head_commit.message, 'Bump version')"
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASS }}
