name: Test Docker

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches: [ master ]

jobs:
  Test-Docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build container
      run: |
        make docker-build
    - name: Run tests
      run: |
        make docker-test